# Generated by Django 6.0.4 on 2026-04-23 21:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ABCChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_occurred', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('intensity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10)),
                ('behaviour_type', models.CharField(choices=[('verbal', 'Verbal'), ('physical', 'Physical'), ('self_harm', 'Self harm'), ('property', 'Property damage'), ('non_verbal', 'Non verbal'), ('other', 'Other')], max_length=12)),
                ('antecedent', models.TextField(help_text='What happened immediately before the behaviour?')),
                ('behaviour', models.TextField(help_text='Describe the behaviour in detail')),
                ('consequence', models.TextField(help_text='What happened as a result? How was it managed?')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('witnesses', models.TextField(blank=True)),
                ('follow_up', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abc_charts', to='clients.client')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abc_charts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_occurred'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalABCChart',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_occurred', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('intensity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10)),
                ('behaviour_type', models.CharField(choices=[('verbal', 'Verbal'), ('physical', 'Physical'), ('self_harm', 'Self harm'), ('property', 'Property damage'), ('non_verbal', 'Non verbal'), ('other', 'Other')], max_length=12)),
                ('antecedent', models.TextField(help_text='What happened immediately before the behaviour?')),
                ('behaviour', models.TextField(help_text='Describe the behaviour in detail')),
                ('consequence', models.TextField(help_text='What happened as a result? How was it managed?')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('witnesses', models.TextField(blank=True)),
                ('follow_up', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical abc chart',
                'verbose_name_plural': 'historical abc charts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
