# Generated by Django 6.0.4 on 2026-04-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='is_published',
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('custom', 'Custom')], default='day', max_length=10),
        ),
    ]
