# Generated by Django 6.0.4 on 2026-04-23 21:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField()),
                ('mood', models.CharField(blank=True, choices=[('happy', 'Happy'), ('calm', 'Calm'), ('anxious', 'Anxious'), ('agitated', 'Agitated'), ('low', 'Low'), ('confused', 'Confused')], max_length=10)),
                ('appetite', models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('refused', 'Refused')], max_length=10)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=10)),
                ('oxygen_level', models.IntegerField(blank=True, null=True)),
                ('fluid_intake_ml', models.IntegerField(blank=True, null=True)),
                ('food_intake', models.CharField(blank=True, max_length=200)),
                ('bowel_movement', models.BooleanField(default=False)),
                ('sleep_quality', models.CharField(blank=True, max_length=100)),
                ('observations', models.TextField(blank=True)),
                ('concerns', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to='clients.client')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalHealthReport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_recorded', models.DateTimeField()),
                ('mood', models.CharField(blank=True, choices=[('happy', 'Happy'), ('calm', 'Calm'), ('anxious', 'Anxious'), ('agitated', 'Agitated'), ('low', 'Low'), ('confused', 'Confused')], max_length=10)),
                ('appetite', models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('refused', 'Refused')], max_length=10)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=10)),
                ('oxygen_level', models.IntegerField(blank=True, null=True)),
                ('fluid_intake_ml', models.IntegerField(blank=True, null=True)),
                ('food_intake', models.CharField(blank=True, max_length=200)),
                ('bowel_movement', models.BooleanField(default=False)),
                ('sleep_quality', models.CharField(blank=True, max_length=100)),
                ('observations', models.TextField(blank=True)),
                ('concerns', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical health report',
                'verbose_name_plural': 'historical health reports',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
