# Generated by Django 6.0.4 on 2026-04-22 21:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIncident',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('fall', 'Fall'), ('medication', 'Medication error'), ('behaviour', 'Behaviour'), ('injury', 'Injury'), ('safeguarding', 'Safeguarding'), ('near_miss', 'Near miss'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('closed', 'Closed')], default='open', max_length=15)),
                ('date_occurred', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('immediate_action', models.TextField(blank=True)),
                ('follow_up', models.TextField(blank=True)),
                ('witnesses', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical incident',
                'verbose_name_plural': 'historical incidents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('fall', 'Fall'), ('medication', 'Medication error'), ('behaviour', 'Behaviour'), ('injury', 'Injury'), ('safeguarding', 'Safeguarding'), ('near_miss', 'Near miss'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('closed', 'Closed')], default='open', max_length=15)),
                ('date_occurred', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('immediate_action', models.TextField(blank=True)),
                ('follow_up', models.TextField(blank=True)),
                ('witnesses', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='clients.client')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_occurred'],
            },
        ),
    ]
