# Generated by Django 6.0.4 on 2026-04-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rostering', '0002_remove_shift_is_published_shift_shift_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='clocked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='clocked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('missed', 'Missed')], default='scheduled', max_length=12),
        ),
    ]
